export const nodesD = [
  {
    name: "Advokat",
    id: 0,
    group: "Others",
    Region: "DKI Jakarta",
    Eigen_Weighted: 0.4364,
    Page_Rank_Values: 0.0702,
  },
  {
    name: "Astra Group Jakpus",
    id: 1,
    group: "Astra Group",
    Region: "Jakpus",
    Eigen_Weighted: 0.1872,
    Page_Rank_Values: 0.0205,
  },
  {
    name: "Astra Group Jaksel",
    id: 2,
    group: "Astra Group",
    Region: "Jaksel",
    Eigen_Weighted: 0.1895,
    Page_Rank_Values: 0.0205,
  },
  {
    name: "Astra Group Jaktim",
    id: 3,
    group: "Astra Group",
    Region: "Jaktim",
    Eigen_Weighted: 0.3462,
    Page_Rank_Values: 0.0245,
  },
  {
    name: "Astra Group Jakut",
    id: 4,
    group: "Astra Group",
    Region: "Jakut",
    Eigen_Weighted: 0.3462,
    Page_Rank_Values: 0.0245,
  },
  {
    name: "Astra Group Kab. Bekasi",
    id: 5,
    group: "Astra Group",
    Region: "Kab. Bekasi",
    Eigen_Weighted: 0.5866,
    Page_Rank_Values: 0.0352,
  },
  {
    name: "Astra Group Kab. Bogor",
    id: 6,
    group: "Astra Group",
    Region: "Kab. Bogor",
    Eigen_Weighted: 0.2803,
    Page_Rank_Values: 0.029,
  },
  {
    name: "Astra Group Kab. Karawang",
    id: 7,
    group: "Astra Group",
    Region: "Kab. Karawang",
    Eigen_Weighted: 0.5866,
    Page_Rank_Values: 0.0352,
  },
  {
    name: "CIR",
    id: 8,
    group: "Astra Group",
    Region: "NA",
    Eigen_Weighted: 0.5356,
    Page_Rank_Values: 0.0413,
  },
  {
    name: "Disnaker DKI",
    id: 9,
    group: "Government",
    Region: "DKI Jakarta",
    Eigen_Weighted: 0.3484,
    Page_Rank_Values: 0.0347,
  },
  {
    name: "Disnaker Jabar",
    id: 10,
    group: "Government",
    Region: "Jabar",
    Eigen_Weighted: 0.6748,
    Page_Rank_Values: 0.0445,
  },
  {
    name: "Disnaker Kab. Bekasi",
    id: 11,
    group: "Government",
    Region: "Kab. Bekasi",
    Eigen_Weighted: 0.5831,
    Page_Rank_Values: 0.0241,
  },
  {
    name: "Disnaker Kab. Bogor",
    id: 12,
    group: "Government",
    Region: "Kab. Bogor",
    Eigen_Weighted: 0.347,
    Page_Rank_Values: 0.0231,
  },
  {
    name: "Disnaker Kab. Karawang",
    id: 13,
    group: "Government",
    Region: "Kab. Karawang",
    Eigen_Weighted: 0.5831,
    Page_Rank_Values: 0.0241,
  },
  {
    name: "DPC SP Jaktim",
    id: 14,
    group: "Union",
    Region: "Jaktim",
    Eigen_Weighted: 0.1806,
    Page_Rank_Values: 0.0233,
  },
  {
    name: "DPC SP Jakut",
    id: 15,
    group: "Union",
    Region: "Jakut",
    Eigen_Weighted: 0.2174,
    Page_Rank_Values: 0.0233,
  },
  {
    name: "DPC SP Kab. Bekasi",
    id: 16,
    group: "Union",
    Region: "Kab. Bekasi",
    Eigen_Weighted: 0.2962,
    Page_Rank_Values: 0.0212,
  },
  {
    name: "DPC SP Kab. Bogor",
    id: 17,
    group: "Union",
    Region: "Kab. Bogor",
    Eigen_Weighted: 0.1617,
    Page_Rank_Values: 0.02,
  },
  {
    name: "DPC SP Kab. Karawang",
    id: 18,
    group: "Union",
    Region: "Kab. Karawang",
    Eigen_Weighted: 0.2962,
    Page_Rank_Values: 0.0212,
  },
  {
    name: "MA",
    id: 19,
    group: "Others",
    Region: "Nasional",
    Eigen_Weighted: 0.1495,
    Page_Rank_Values: 0.0288,
  },
  {
    name: "PHI DKI",
    id: 20,
    group: "Others",
    Region: "DKI Jakarta",
    Eigen_Weighted: 0.32,
    Page_Rank_Values: 0.0547,
  },
  {
    name: "PHI Jabar",
    id: 21,
    group: "Others",
    Region: "Jabar",
    Eigen_Weighted: 0.382,
    Page_Rank_Values: 0.0553,
  },
  {
    name: "SP AG Jaktim",
    id: 22,
    group: "Union",
    Region: "Jaktim",
    Eigen_Weighted: 0.2736,
    Page_Rank_Values: 0.032,
  },
  {
    name: "SP AG Jakut",
    id: 23,
    group: "Union",
    Region: "Jakut",
    Eigen_Weighted: 0.2736,
    Page_Rank_Values: 0.032,
  },
  {
    name: "SP AG Kab. Bekasi",
    id: 24,
    group: "Union",
    Region: "Kab. Bekasi",
    Eigen_Weighted: 0.3712,
    Page_Rank_Values: 0.0282,
  },
  {
    name: "SP AG Kab. Bogor",
    id: 25,
    group: "Union",
    Region: "Kab. Bogor",
    Eigen_Weighted: 0.194,
    Page_Rank_Values: 0.0271,
  },
  {
    name: "SP AG Kab. Karawang",
    id: 26,
    group: "Union",
    Region: "Kab. Karawang",
    Eigen_Weighted: 0.3712,
    Page_Rank_Values: 0.0282,
  },
  {
    name: "Sudinaker Jakpus",
    id: 27,
    group: "Government",
    Region: "Jakpus",
    Eigen_Weighted: 0.2189,
    Page_Rank_Values: 0.0184,
  },
  {
    name: "Sudinaker Jaksel",
    id: 28,
    group: "Government",
    Region: "Jaksel",
    Eigen_Weighted: 0.2295,
    Page_Rank_Values: 0.0184,
  },
  {
    name: "Sudinaker Jaktim",
    id: 29,
    group: "Government",
    Region: "Jaktim",
    Eigen_Weighted: 0.4234,
    Page_Rank_Values: 0.0236,
  },
  {
    name: "Sudinaker Jakut",
    id: 30,
    group: "Government",
    Region: "Jakut",
    Eigen_Weighted: 0.4234,
    Page_Rank_Values: 0.0236,
  },
  {
    name: "UPTD Bogor",
    id: 32,
    group: "Government",
    Region: "Kab. Bogor",
    Eigen_Weighted: 0.3739,
    Page_Rank_Values: 0.027,
  },
  {
    name: "UPTD Karawang - Bekasi",
    id: 31,
    group: "Government",
    Region: "Kab. Karawang - Bekasi",
    Eigen_Weighted: 1,
    Page_Rank_Values: 0.0421,
  },
];

export const linksD = [
  {
    source: "Astra Group Jakpus",
    target: "Advokat",
    weight: 1,
  },
  {
    source: "Astra Group Jaksel",
    target: "Advokat",
    weight: 1,
  },
  {
    source: "Astra Group Jaktim",
    target: "Advokat",
    weight: 1,
  },
  {
    source: "Astra Group Jakut",
    target: "Advokat",
    weight: 1,
  },
  {
    source: "Astra Group Kab. Bekasi",
    target: "Advokat",
    weight: 1,
  },
  {
    source: "Astra Group Kab. Bogor",
    target: "Advokat",
    weight: 1,
  },
  {
    source: "Astra Group Kab. Karawang",
    target: "Advokat",
    weight: 1,
  },
  {
    source: "CIR",
    target: "Advokat",
    weight: 1,
  },
  {
    source: "PHI DKI",
    target: "Advokat",
    weight: 1.5,
  },
  {
    source: "PHI Jabar",
    target: "Advokat",
    weight: 1.5,
  },
  {
    source: "CIR",
    target: "Astra Group Jakpus",
    weight: 1.5,
  },
  {
    source: "Disnaker DKI",
    target: "Astra Group Jakpus",
    weight: 1.5,
  },
  {
    source: "Sudinaker Jakpus",
    target: "Astra Group Jakpus",
    weight: 2,
  },
  {
    source: "CIR",
    target: "Astra Group Jaksel",
    weight: 1.5,
  },
  {
    source: "Disnaker DKI",
    target: "Astra Group Jaksel",
    weight: 1.5,
  },
  {
    source: "Sudinaker Jaksel",
    target: "Astra Group Jaksel",
    weight: 2,
  },
  {
    source: "CIR",
    target: "Astra Group Jaktim",
    weight: 2,
  },
  {
    source: "Disnaker DKI",
    target: "Astra Group Jaktim",
    weight: 1.5,
  },
  {
    source: "SP AG Jaktim",
    target: "Astra Group Jaktim",
    weight: 3,
  },
  {
    source: "Sudinaker Jaktim",
    target: "Astra Group Jaktim",
    weight: 2,
  },
  {
    source: "CIR",
    target: "Astra Group Jakut",
    weight: 2,
  },
  {
    source: "Disnaker DKI",
    target: "Astra Group Jakut",
    weight: 1.5,
  },
  {
    source: "SP AG Jakut",
    target: "Astra Group Jakut",
    weight: 3,
  },
  {
    source: "Sudinaker Jakut",
    target: "Astra Group Jakut",
    weight: 2,
  },
  {
    source: "CIR",
    target: "Astra Group Kab. Bekasi",
    weight: 2,
  },
  {
    source: "Disnaker Jabar",
    target: "Astra Group Kab. Bekasi",
    weight: 1,
  },
  {
    source: "Disnaker Kab. Bekasi",
    target: "Astra Group Kab. Bekasi",
    weight: 2,
  },
  {
    source: "SP AG Kab. Bekasi",
    target: "Astra Group Kab. Bekasi",
    weight: 3,
  },
  {
    source: "UPTD Karawang - Bekasi",
    target: "Astra Group Kab. Bekasi",
    weight: 1.5,
  },
  {
    source: "CIR",
    target: "Astra Group Kab. Bogor",
    weight: 1.5,
  },
  {
    source: "Disnaker Kab. Bogor",
    target: "Astra Group Kab. Bogor",
    weight: 2,
  },
  {
    source: "SP AG Kab. Bogor",
    target: "Astra Group Kab. Bogor",
    weight: 3,
  },
  {
    source: "UPTD Bogor",
    target: "Astra Group Kab. Bogor",
    weight: 1.5,
  },
  {
    source: "CIR",
    target: "Astra Group Kab. Karawang",
    weight: 2,
  },
  {
    source: "Disnaker Jabar",
    target: "Astra Group Kab. Karawang",
    weight: 1,
  },
  {
    source: "Disnaker Kab. Karawang",
    target: "Astra Group Kab. Karawang",
    weight: 2,
  },
  {
    source: "SP AG Kab. Karawang",
    target: "Astra Group Kab. Karawang",
    weight: 3,
  },
  {
    source: "UPTD Karawang - Bekasi",
    target: "Astra Group Kab. Karawang",
    weight: 1.5,
  },
  {
    source: "Astra Group Jakpus",
    target: "CIR",
    weight: 2,
  },
  {
    source: "Astra Group Jaksel",
    target: "CIR",
    weight: 2,
  },
  {
    source: "Astra Group Jaktim",
    target: "CIR",
    weight: 2,
  },
  {
    source: "Astra Group Jakut",
    target: "CIR",
    weight: 2,
  },
  {
    source: "Astra Group Kab. Bekasi",
    target: "CIR",
    weight: 2,
  },
  {
    source: "Astra Group Kab. Bogor",
    target: "CIR",
    weight: 2,
  },
  {
    source: "Astra Group Kab. Karawang",
    target: "CIR",
    weight: 2,
  },
  {
    source: "CIR",
    target: "Disnaker DKI",
    weight: 2.5,
  },
  {
    source: "Sudinaker Jakpus",
    target: "Disnaker DKI",
    weight: 1.5,
  },
  {
    source: "Sudinaker Jaksel",
    target: "Disnaker DKI",
    weight: 1.5,
  },
  {
    source: "Sudinaker Jaktim",
    target: "Disnaker DKI",
    weight: 1.5,
  },
  {
    source: "Sudinaker Jakut",
    target: "Disnaker DKI",
    weight: 1.5,
  },
  {
    source: "CIR",
    target: "Disnaker Jabar",
    weight: 2.5,
  },
  {
    source: "Disnaker Kab. Bekasi",
    target: "Disnaker Jabar",
    weight: 1.5,
  },
  {
    source: "Disnaker Kab. Bogor",
    target: "Disnaker Jabar",
    weight: 1.5,
  },
  {
    source: "Disnaker Kab. Karawang",
    target: "Disnaker Jabar",
    weight: 1.5,
  },
  {
    source: "UPTD Bogor",
    target: "Disnaker Jabar",
    weight: 2,
  },
  {
    source: "UPTD Karawang - Bekasi",
    target: "Disnaker Jabar",
    weight: 2,
  },
  {
    source: "Astra Group Kab. Bekasi",
    target: "Disnaker Kab. Bekasi",
    weight: 3,
  },
  {
    source: "CIR",
    target: "Disnaker Kab. Bekasi",
    weight: 3,
  },
  {
    source: "Disnaker Jabar",
    target: "Disnaker Kab. Bekasi",
    weight: 1.5,
  },
  {
    source: "SP AG Kab. Bekasi",
    target: "Disnaker Kab. Bekasi",
    weight: 3,
  },
  {
    source: "Astra Group Kab. Bogor",
    target: "Disnaker Kab. Bogor",
    weight: 2.5,
  },
  {
    source: "CIR",
    target: "Disnaker Kab. Bogor",
    weight: 2,
  },
  {
    source: "Disnaker Jabar",
    target: "Disnaker Kab. Bogor",
    weight: 1.5,
  },
  {
    source: "SP AG Kab. Bogor",
    target: "Disnaker Kab. Bogor",
    weight: 2.5,
  },
  {
    source: "Astra Group Kab. Karawang",
    target: "Disnaker Kab. Karawang",
    weight: 3,
  },
  {
    source: "CIR",
    target: "Disnaker Kab. Karawang",
    weight: 3,
  },
  {
    source: "Disnaker Jabar",
    target: "Disnaker Kab. Karawang",
    weight: 1.5,
  },
  {
    source: "SP AG Kab. Karawang",
    target: "Disnaker Kab. Karawang",
    weight: 3,
  },
  {
    source: "Astra Group Jaktim",
    target: "DPC SP Jaktim",
    weight: 1.5,
  },
  {
    source: "SP AG Jaktim",
    target: "DPC SP Jaktim",
    weight: 2,
  },
  {
    source: "Sudinaker Jaktim",
    target: "DPC SP Jaktim",
    weight: 1.5,
  },
  {
    source: "Astra Group Jakut",
    target: "DPC SP Jakut",
    weight: 2.5,
  },
  {
    source: "SP AG Jakut",
    target: "DPC SP Jakut",
    weight: 2,
  },
  {
    source: "Sudinaker Jakut",
    target: "DPC SP Jakut",
    weight: 1.5,
  },
  {
    source: "Astra Group Kab. Bekasi",
    target: "DPC SP Kab. Bekasi",
    weight: 2,
  },
  {
    source: "Disnaker Kab. Bekasi",
    target: "DPC SP Kab. Bekasi",
    weight: 1.5,
  },
  {
    source: "SP AG Kab. Bekasi",
    target: "DPC SP Kab. Bekasi",
    weight: 2,
  },
  {
    source: "Astra Group Kab. Bogor",
    target: "DPC SP Kab. Bogor",
    weight: 1.5,
  },
  {
    source: "Disnaker Kab. Bogor",
    target: "DPC SP Kab. Bogor",
    weight: 1.5,
  },
  {
    source: "SP AG Kab. Bogor",
    target: "DPC SP Kab. Bogor",
    weight: 3,
  },
  {
    source: "Astra Group Kab. Karawang",
    target: "DPC SP Kab. Karawang",
    weight: 2,
  },
  {
    source: "Disnaker Kab. Karawang",
    target: "DPC SP Kab. Karawang",
    weight: 1.5,
  },
  {
    source: "SP AG Kab. Karawang",
    target: "DPC SP Kab. Karawang",
    weight: 2,
  },
  {
    source: "Advokat",
    target: "MA",
    weight: 2,
  },
  {
    source: "CIR",
    target: "MA",
    weight: 1,
  },
  {
    source: "Advokat",
    target: "PHI DKI",
    weight: 2.5,
  },
  {
    source: "CIR",
    target: "PHI DKI",
    weight: 1.5,
  },
  {
    source: "MA",
    target: "PHI DKI",
    weight: 2,
  },
  {
    source: "SP AG Jaktim",
    target: "PHI DKI",
    weight: 1.5,
  },
  {
    source: "SP AG Jakut",
    target: "PHI DKI",
    weight: 1.5,
  },
  {
    source: "Advokat",
    target: "PHI Jabar",
    weight: 2.5,
  },
  {
    source: "CIR",
    target: "PHI Jabar",
    weight: 1.5,
  },
  {
    source: "MA",
    target: "PHI Jabar",
    weight: 2,
  },
  {
    source: "SP AG Kab. Bekasi",
    target: "PHI Jabar",
    weight: 1.5,
  },
  {
    source: "SP AG Kab. Bogor",
    target: "PHI Jabar",
    weight: 1.5,
  },
  {
    source: "SP AG Kab. Karawang",
    target: "PHI Jabar",
    weight: 1.5,
  },
  {
    source: "Astra Group Jaktim",
    target: "SP AG Jaktim",
    weight: 3,
  },
  {
    source: "PHI DKI",
    target: "SP AG Jaktim",
    weight: 1.5,
  },
  {
    source: "Sudinaker Jaktim",
    target: "SP AG Jaktim",
    weight: 2.5,
  },
  {
    source: "Astra Group Jakut",
    target: "SP AG Jakut",
    weight: 3,
  },
  {
    source: "PHI DKI",
    target: "SP AG Jakut",
    weight: 1.5,
  },
  {
    source: "Sudinaker Jakut",
    target: "SP AG Jakut",
    weight: 2.5,
  },
  {
    source: "Astra Group Kab. Bekasi",
    target: "SP AG Kab. Bekasi",
    weight: 2.5,
  },
  {
    source: "Disnaker Kab. Bekasi",
    target: "SP AG Kab. Bekasi",
    weight: 2.5,
  },
  {
    source: "PHI Jabar",
    target: "SP AG Kab. Bekasi",
    weight: 1.5,
  },
  {
    source: "Astra Group Kab. Bogor",
    target: "SP AG Kab. Bogor",
    weight: 2,
  },
  {
    source: "Disnaker Kab. Bogor",
    target: "SP AG Kab. Bogor",
    weight: 2,
  },
  {
    source: "PHI Jabar",
    target: "SP AG Kab. Bogor",
    weight: 1.5,
  },
  {
    source: "Astra Group Kab. Karawang",
    target: "SP AG Kab. Karawang",
    weight: 2.5,
  },
  {
    source: "Disnaker Kab. Karawang",
    target: "SP AG Kab. Karawang",
    weight: 2.5,
  },
  {
    source: "PHI Jabar",
    target: "SP AG Kab. Karawang",
    weight: 1.5,
  },
  {
    source: "Astra Group Jakpus",
    target: "Sudinaker Jakpus",
    weight: 2.5,
  },
  {
    source: "CIR",
    target: "Sudinaker Jakpus",
    weight: 2,
  },
  {
    source: "Disnaker DKI",
    target: "Sudinaker Jakpus",
    weight: 1.5,
  },
  {
    source: "Astra Group Jaksel",
    target: "Sudinaker Jaksel",
    weight: 3,
  },
  {
    source: "CIR",
    target: "Sudinaker Jaksel",
    weight: 2,
  },
  {
    source: "Disnaker DKI",
    target: "Sudinaker Jaksel",
    weight: 1.5,
  },
  {
    source: "Astra Group Jaktim",
    target: "Sudinaker Jaktim",
    weight: 3,
  },
  {
    source: "CIR",
    target: "Sudinaker Jaktim",
    weight: 3,
  },
  {
    source: "Disnaker DKI",
    target: "Sudinaker Jaktim",
    weight: 1.5,
  },
  {
    source: "SP AG Jaktim",
    target: "Sudinaker Jaktim",
    weight: 3,
  },
  {
    source: "Astra Group Jakut",
    target: "Sudinaker Jakut",
    weight: 3,
  },
  {
    source: "CIR",
    target: "Sudinaker Jakut",
    weight: 3,
  },
  {
    source: "Disnaker DKI",
    target: "Sudinaker Jakut",
    weight: 1.5,
  },
  {
    source: "SP AG Jakut",
    target: "Sudinaker Jakut",
    weight: 3,
  },
  {
    source: "Astra Group Kab. Bogor",
    target: "UPTD Bogor",
    weight: 2.5,
  },
  {
    source: "CIR",
    target: "UPTD Bogor",
    weight: 1.5,
  },
  {
    source: "Disnaker Jabar",
    target: "UPTD Bogor",
    weight: 1.5,
  },
  {
    source: "Disnaker Kab. Bogor",
    target: "UPTD Bogor",
    weight: 1.5,
  },
  {
    source: "SP AG Kab. Bogor",
    target: "UPTD Bogor",
    weight: 2.5,
  },
  {
    source: "Astra Group Kab. Bekasi",
    target: "UPTD Karawang - Bekasi",
    weight: 3,
  },
  {
    source: "Astra Group Kab. Karawang",
    target: "UPTD Karawang - Bekasi",
    weight: 3,
  },
  {
    source: "CIR",
    target: "UPTD Karawang - Bekasi",
    weight: 2,
  },
  {
    source: "Disnaker Jabar",
    target: "UPTD Karawang - Bekasi",
    weight: 1.5,
  },
  {
    source: "Disnaker Kab. Bekasi",
    target: "UPTD Karawang - Bekasi",
    weight: 2,
  },
  {
    source: "Disnaker Kab. Karawang",
    target: "UPTD Karawang - Bekasi",
    weight: 2,
  },
  {
    source: "SP AG Kab. Bekasi",
    target: "UPTD Karawang - Bekasi",
    weight: 2,
  },
  {
    source: "SP AG Kab. Karawang",
    target: "UPTD Karawang - Bekasi",
    weight: 2,
  },
];
